### ISSUE TITLE
PHP warning when running with -v on windows for COMPOSER_COMPILE_TASK

### ISSUE THREAD

**Issue by demeritcowboy** [civicrm/composer-compile-plugin#15]
`Warning: Use of undefined constant COMPOSER_COMPILE_TASK - assumed 'COMPOSER_COMPILE_TASK' (this will throw an Error in a future version of PHP) in Command line code on line 1`

This line puts double-quotes around it: https://github.com/civicrm/composer-compile-plugin/blob/af9686c4511ad4d2dde3c32aafa4637579e1085d/src/Handler/PhpMethodHandler.php#L21

On windows the double-quotes disappear at some point along the way and so php thinks you're using a constant that hasn't been defined.

Since shell escaping is hard enough as it is and on windows is extra-bizarre, just putting this as a placeholder for now. With a quickie test it works to just put single quotes in that code line, i.e. `\'`. I might test that out a bit more.

**Comment by totten** [comment]
@demeritcowboy Hmm... that sounds like a bug in `escapeshellarg()`.

But maybe #16 would make the question moot?

Relatedly - do the tests run on your Windows box? In principle, either `tests/MultiStepTaskTest.php` or `tests/ScssPhpMethodTest.php` should involve the transfer of `@php-method` tasks.

**Comment by demeritcowboy** [comment]
> Relatedly - do the tests run on your Windows box?

Ha ha ha ha ha.

```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
EEEEEEEEEEEEEEEEEEEEEEE

Time: 3.51 seconds, Memory: 12.00 MB

There were 23 errors:
```

But it's hard to tell really because of this line in IntegrationTestCase: `PH::runOk(['if [ -d @DIR ]; then rm -rf @DIR ; fi', 'DIR' => $dir]);`

**Comment by totten** [comment]
> ```
> PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
> EEEEEEEEEEEEEEEEEEEEEEE
>
> Time: 3.51 seconds, Memory: 12.00 MB
>
> There were 23 errors:
> ```

Hmm... well... at least... it didn't fatal-out! Or reformat the hard-drive...
