### ISSUE TITLE
putenv/getenv doesn't work in php when thread safety is disabled

### ISSUE THREAD

**Issue by demeritcowboy** [civicrm/composer-compile-plugin#17]
Apparently some distributions of php have `Thread Safety => disabled` (e.g. `php -i | grep Thread`). This makes getenv always return false, so it can't get the task. I don't have an immediate workaround other than to do it on another system and transfer it over, or instead write to known fixed filename and then read that back. Mostly putting this here in case other people run into this.

It's in src/TaskTransfer.php in export() and import().

```
WARNING: Failed to read compilation-task from COMPOSER_COMPILE_TASK. Please use "composer compile".
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid file reference (tpl-file=NULL) in .../sites/all/modules/civicrm/vendor/civicrm/composer-compile-lib/src/Tasks/Template.php:62
Stack trace:
#0 .../sites/all/modules/civicrm/vendor/civicrm/composer-compile-lib/src/Tasks/Template.php(21): CCL\Tasks\Template::assertFileField(Array, 'tpl-file')
#1 .../sites/all/modules/civicrm/vendor/civicrm/composer-compile-lib/src/Tasks.php(24): CCL\Tasks\Template::compile(Array)
#2 Command line code(1): CCL\Tasks::template(Array)
#3 {main}
  thrown in .../sites/all/modules/civicrm/vendor/civicrm/composer-compile-lib/src/Tasks/Template.php on line 62
> @php -r 'require_once '\''.../sites/all/modules/civicrm/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::template($GLOBALS["COMPOSER_COMPILE_TASK"]);'
Script @php -r 'require_once '\''.../sites/all/modules/civicrm/vendor/autoload.php'\''; Civi\CompilePlugin\TaskTransfer::import(); \CCL\Tasks::template($GLOBALS["COMPOSER_COMPILE_TASK"]);' handling the shell-runner event returned with error code 255
```

**Comment by totten** [comment]
I'm a little surprised - `composer` itself uses `getenv()`/`putenv()` several times. If the deployment doesn't support `getenv()`, then I would expect it to face more issues. (But, yeah, maybe `TaskTransfer` is special in how the env is mandatory.) One might be best off having different PHP binaries/build-options (e.g. one binary/build for integration with HTTPD-integration; another for CLI).

For updating this package... at a minimum, we could have it skip compilation and show better warnings if the system lacks `getenv()` support. Maybe print a link to some doc/blurb about the issue.

FWIW, an alternate task-transfer protocol based on `$argv` would probably be workable, e.g. (pseudocode)

```php
$tmp = '/tmp/task-def.json';
file_put_contents($tmp, json_encode(...));
exec("php -r 'TaskTransfer::importArgv($argv); ...runtask...' " . escapeshellarg($tmp));
```

That would mean a bit more disk I/O, and the change would require a general search/update on every file that mentions `TaskTransfer`.

**Comment by demeritcowboy** [comment]
Interesting - you made me look at composer and it looks like what it actually does is this: https://github.com/composer/composer/blob/3556f6efa5171a50be1123da55ab612d6d27631b/src/Composer/Util/Platform.php#L34

When I test that technique of also setting $_SERVER and $_ENV with compile-plugin, it works!

**Comment by jackrabbithanna** [comment]
I maybe experiencing this issue:
https://github.com/civicrm/composer-compile-lib/issues/3

in src/TaskTransfer.php . .the putenv() in export(), sets the environmental variable, but it is unreadable in import()

This is only for composer 2, not composer 1

Drawing from demeritcowboy's comment, adding a line to the export() function makes it work:
```
$data = base64_encode(gzencode(json_encode($task->definition)));
        if (strlen($data) < self::MAX_ENV_SIZE) {
            putenv(self::ENV_VAR . '=' . $data);
            $_SERVER[self::ENV_VAR] = $_ENV[self::ENV_VAR] = $data; // added this
        } else {
```
