### ISSUE TITLE
PHP 8.1 / PHP 8.0 compatibility issue

### ISSUE THREAD

**Issue by olstjos** [civicrm/composer-compile-plugin#22]
this plugin is not compatible with PHP 8.1 / PHP 8.0
smoke billows out of this area:

```  [TypeError]                                                                                                                                                                                             
  Composer\EventDispatcher\Event::__construct(): Argument #1 ($name) must be of type string, null given, called in vendor/civicrm/composer-compile-plugin/src/Event  
  /CompileTaskEvent.php on line 55```

**Comment by totten** [comment]
@olstjos Are you running v0.18?

I would expect that #20's 9787277c8ba6fc2a6916ec4373c03759d77abd00 would fix that.

(I can't see any other path that would provide `null` value of `$name`. But if you do get the error on 0.18, could you post a bigger backtrace?)

**Comment by totten** [comment]
I've run this a bit on php81 and updated the test-matrix to include php81 (#23).

Please feel free to reopen if there's still an issue.
